apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmv-inn-app
  namespace: grupoguma
  labels:
    app: gmv-inn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gmv-inn-app
  template:
    metadata:
      labels:
        app: gmv-inn-app
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cn-gmv-inn-app
          image: gumadesarrollo/gmvinnova:v1.0.{{BUILD_NUMBER}}
          imagePullPolicy: Always
          volumeMounts:
            - name: storage
              mountPath: /data/web/storage
              subPath: storageApp
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "72m"
            limits:
              memory: "128Mi"
              cpu: "144m"
